const ACTION ={
    NOVA_POST_REQUEST : 'NOVA_POST_REQUEST',
    NOVA_POST_ERROR : 'NOVA_POST_ERROR',

    // CITIES CONSTANTS
    GET_CITIES_DATA_ACTION : 'GET_CITIES_DATA_ACTION',
    GET_CITIES_DATA_SUCCESS : 'GET_CITIES_DATA_SUCCESS',
    
    SET_SELECTED_CITY : 'SET_SELECTED_CITY',

    SET_SELECTED_CITY_REF : 'SET_SELECTED_CITY_REF',

    // WAREHOUSES CONSTANTS
    GET_WAREHOUSES_DATA_ACTION : 'GET_WAREHOUSES_DATA_ACTION',
    GET_WAREHOUSES_DATA_SUCCESS : 'GET_WAREHOUSES_DATA_SUCCESS',

    SET_SELECTED_WAREHOUSE : 'SET_SELECTED_WAREHOUSE',

}
export default ACTION;


